services:
  web:
    image: python:3.13-alpine
    build:
      context: "https://github.com/andetazz/parqueadero12.git"
      dockerfile: Dockerfile
    volumes:
      - app-data:/app
volumes:
  app-data:

      